/# This file was \*autogenerated\* .*/d
/from sage\.all_cmdline import .*/d
:l
s/_sage_const_\([[:digit:]]\+\)p\([[:digit:]]\+\)/RealNumber('\1.\2')/
s/_sage_const_\([[:digit:]]\+\)/Integer(\1)/
/_sage_const_/bl
/\(\(Integer\|RealNumber\)('\?[[:alnum:]]\+'\?)\)[[:blank:]]\+=[[:blank:]]\+\1/d
/^[[:blank:]]*$/!{h;b}
x;/^[[:blank:]]*$/!{g;b}
g;d
