#!/usr/bin/env bash

compile_file() {
    name=${1%.sage}
    echo "Compiling ${name}.sage"
    sage -preparse "${name}.sage"
    if [[ -e "${name}.py" ]]; then
	rm "${name}.py"
    fi
    mv "${name}.sage.py" "${name}.py"
    rm "${name}.sage"
    sed -i '/# This file was \*autogenerated\* .*/d' "${name}.py"
    sed -i '/from sage\.all_cmdline import .*/d' "${name}.py"
}

compile_directory() {
    echo "Compiling ${1}"
    for file in ${1}/*; do
	if [[ -d $file ]]; then
	    compile_directory "$file"
	elif [[ "$file" =~ .+\.sage ]]; then
	    compile_file "$file"
	fi
    done
    if ! [[ -e "${1}/__init__.py" ]]; then
	touch "${1}/__init__.py"
    fi
}

target="modular_method"
if ! [[ -e "$target" ]] || ! [[ -d "$target" ]]; then
    mkdir "$target"
fi
cp -r src/* modular_method/    
compile_directory "$target"
