* Legend
Part of load.sage (*)
Partial documentation (-)
Fully documented, except examples (+)
Fully documented (#)
Stylized (!)
Should scrap (%)

* File overview

** database/

** diophantine_equations/
Code to analyze diophantine equations

*** conditions.sage (*#)
Conditions on diophantine variables
- Add decorator for conditional functions

*** Frey_curve_construction.sage
Some functions to make Frey curves

*** newform_elimination.sage (*-) -> modular_forms/
Methods for eliminating newforms
- Add better tracking system for primes

*** prime_power.sage (*+)
Methods for analyzing diophantine equations of the form polynomial equals prime power
** elliptic_curves/
Code for elliptic curves
*** conjugate.sage (*-)
Method for conjugating curve
- Does this do the same as change_ring?
- Move to other file or scrap
*** frey_curves.sage (*+)
Frey curve classes
*** Q-curves.sage (*#)
Implementation of Q-curves
- Replace guessed degrees by sage isogeny code
*** twist.sage (*+)
Methods for computing (with) twists of elliptic curves
** examples/
Examples of various things
*** counter example alpha in OK.sage
Data to show that not every cocycle with values in {\pm 1} is the
coboundary of a function to the ring of integers of a field.
*** Dieulefait.sage
Repeated conductor computations from an article of Dieulefait
Considering the diophantine equation x^4 + c*y^2 = z^l
! Uses deprecated DiophantineAnalyzer
- Is it in database?
- Remove or move and update
*** frey curve conductor (-)
Conductor computations of frey curves by Merel and Ellenberg
Equations a^n + b^n = 2*c^n, a^n + b^n = c^2, a^n + b^n = c^2,
a^n + b^n = c^3, a^4 + b^2 = c^n
- Is it in database?
- Remove or move and update
*** literature/
Examples from the literature
- Move into database if not already there
**** Bennet-Chen-2014.sage (-)
Frey curve computations of frey curves by Bennet and Chen
Equation a^2 + b^6 = c^l
- Is it in database?
- Remove or move and update
**** Bennet-Chen-Dahmen-Yazdani-2014.sage (-)
Frey curve computations of frey curves by Bennet, Chen, Dahmen and
Yazdani
Equation a^3 + b^(3*n) = c^2
- Is it in database?
- Remove or move and update
**** Dieulefait-Freitas-2014.sage (-)
Frey curve computations of frey curves by Dieulefait and Freitas
Equations x^5 + y^5 = 2*z^l, x^5 + y^5 = 3*z^l
- Is it in database?
- Remove or move and update
**** Dieulefait-Urroz-2008.sage (-)
Frey curve computations of frey curves by Dieulefait and Urroz
Equation x^4 + 2*y^2 = z^l
- Is it in database?
- Remove or move and update
*** Q-curve examples.sage (-)
Examples of Q-curves
- Is it in database?
- Remove or move and update
*** Q-curve families.sage (-)
Families of Q-curves
- Is it in database?
- Remove or move and update
*** Q-curve tests.sage
Small tests on Q-curves with two isogeny
- Superceded by new tests?
- Remove or move and update
*** scr.sage
A check on Tate's algorithm
- Make into a doctest
*** test1.sage
Examples of Tates algorithm
Equations x^l + y^l = z^l, x^2 - 11 = y^l, x^3 - x - 2 = y^l,
x^3 = 13 = y^l, x^4 + x^3 - 3*x^2 + 11*x + 2 = y^l
- Are these in database?
- Remove or move and update
*** test.sage
A test on Tate's algorithm
- Make into a doctest of performTatesAlgorithm
*** tmp2.sage
Old conductor computations (no results)
Equations x^l + y^l = z^2 and x^l + y^l = z^3
- Are these in database?
! Uses the remove DiophantineAnalyzer
** group cohomology/
Results about group cohomology
*** calculations.sage (*+)
Some useful computations in group cohomology
- Make code look nicer
- Rename file?
** L-functions/
*** Euler factors.sage (*+)
Computation of the Euler factor of L-functions of newforms and
elliptic curves.
- Move into newform wrapper and Q-curve class respectively
** linear algebra/
Linear algebra tools
*** matrix operations.sage (*+)
Operations to simplify matrices
! Most functions are very slow
- Is this still in use?
- Remove all unused functions
*** solver.sage (*#)
Method to solve a linear equation over Z with torsion
- Make the code nicer?
** modular_forms/
Code to analyze modular forms
*** newform wrapper.sage (*+)
Wrapper classes around newforms and a new method to get newforms
** number_fields/
Code to analyze number fields
*** dirichlet characters.sage (*#)
Methods related to dirichlet characters
*** field constructors.sage (*#)
Methods to make number fields
- Look into making methods smarter/faster
*** field information.sage (*#)
Methods to analyze number fields
- Join with something else?
*** galois group.sage (*#)
Methods to change galois homomorphisms
- Change name?
*** QuotientIterators (*+)
Methods to iterate over certain quotients
- Is it still used?
- Remove if possible
** p-adics/
Code related to p-adic numbers
*** pAdic_base.sage (*+)
A class giving easy acces to things needed for p-adic computations
*** pAdic_solver.sage (*+)
Methods for finding all pAdic roots of a polynomial up to a given
precision
*** pAdic_tree.sage (*+)
Classes for storing pAdic data in a tree like format
** polynomial/
Code for working with polynomials
*** symmetric_polynomials.sage (*+)
Method for computing with a symmetric polynomial
** Tates_algorithm/ -> elliptic_curves/
Methods for computing conductors of frey curves
*** Papadopoulos.sage (*-)
Unfinished code for Papadopoulus table lookup
- Remove from load path
- Remove or rewrite
*** TatesAlgorithm.sage (*-)
An implementation of Tate's algorithm that works for Frey curves
** tests/
Code for (automated) testing
*** cleanup.sh (+)
Cleanup script
*** code/
Temporary directory for code to be tested
*** generate.sh
Script to generate code from a template
*** Q-curve sage vs magma.sage (-)
Speed test results between sage and magma newform computations
*** results/
Output directory for results (logs) of tests
*** templates/
Templates for tests
**** Q-curve with 2-3-isogeny.sage
Template for a test on a Q-curve with a 2 and a 3-isogeny
**** Q-curve with 2-isogeny.sage
Template for a test on a Q-curve with a 2-isogeny
**** Q-curve with 3-isogeny.sage
Template for a test on a Q-curve with a 3-isogeny
**** run.sage
Template for a wrapper script around a file.
**** test.sage (%)
Old test file
*** testrun_database.sh
A script that tests all .sage files in the database
*** testrun.sh
A script that tests all .sage files in the code directory
