* Legend
Part of load.sage (*)
Partial documentation (-)
Fully documented, except examples (+)
Fully documented (#)
Stylized (!)
Should scrap (%)

* File overview

** database/
A database of examples to use and test the code
*** Bennett-Chen-2012.rst
Computations from "Multi-Frey Q-curve and the Diophantine equation a^2 + b^6 = c^n"
by Michael A. Bennett and Imin Chen
in Algebra & Number Theory, volume 6 (2012), no. 4.
*** Bennett-Chen-Dahmen-Yazdani-2014.rst
Computations from "On the equation a^3 + b^(3 n) = c^2"
by M. A. Bennett, Imin Chen, Sander R. Dahmen and Soroosh Yazdani
in Acta Arithmetica 163 (2014), no. 4, pages 327-343
*** Dieulefait-Freitas-2014.rst
Computations from "The Fermat-type equations x^5 + y^5 = 2 z^p or 3 z^p solved through Q-curves"
by Luis Dieulefait and Nuno Freitas
in Mathematics of Computation, volume 83 (2014), no. 286, pages 917-933
*** Dieulefait-Urroz-2009.rst
Computations from "Solving Fermat-type equations via modular Q-curve over polyquadratic fields"
by Luis Dieulefait and Jorge Jiménez Urroz
in Journal für die reine und angewandte Mathematik, volume 633 (2009), pages 183-195
*** Ellenberg-2002.rst
Computations from "Galois representations attacted to Q-curves and the generalized Fermat equation A^4 + B^2 = C^p"
by Jordan S. Ellenberg
in American Journal of Mathematics, volume 126 (2004), no. 4, pages 763-787
** examples/
Examples of various things
*** counter example alpha in OK.sage
Data to show that not every cocycle with values in {\pm 1} is the
coboundary of a function to the ring of integers of a field.
- Modify to not use matrix_operations.sage
*** Q-curve families.sage (-)
Families of Q-curves
- Is it in database?
- Remove or move and update
*** test1.sage
Examples of Tates algorithm
Equations x^l + y^l = z^l, x^2 - 11 = y^l, x^3 - x - 2 = y^l,
x^3 = 13 = y^l, x^4 + x^3 - 3*x^2 + 11*x + 2 = y^l
- Move and update
** src/
*** diophantine_equations/
 Code to analyze diophantine equations

**** conditions.sage (*#!)
 Conditions on diophantine variables
 - Add decorator for conditional functions

**** Frey_curve_construction.sage
 Some functions to make Frey curves

**** prime_power.sage (*+!)
 Methods for analyzing diophantine equations of the form polynomial equals prime power
 - Integrate with conditions??
 - Keep track of previously computed prime data
 - Combine conditions into one??
*** elliptic_curves/
 Code for elliptic curves
**** frey_curves.sage (*+!)
 Frey curve classes
 - Add verbosity to primes_of_possible_additive_reduction
 - Scrap the methods newforms!!
**** Q-curves.sage (*+!)
 Implementation of Q-curves
 - Replace guessed degrees by sage isogeny code
 - Use new newform wrappers in method newform and split up code
**** tates_algorithm.sage (*+!)
 An implementation of Tate's algorithm that works for Frey curves
**** twist.sage (*#!)
 Methods for computing (with) twists of elliptic curves
*** group cohomology/
 Results about group cohomology
**** calculations.sage (*#!)
 Some useful computations in group cohomology
 - Add generic group cohomology methods
 - Make code look nicer
 - Rename file?
*** L-functions/
**** Euler factors.sage (*+)
 Computation of the Euler factor of L-functions of newforms and
 elliptic curves.
 - Move into newform wrapper and Q-curve class respectively
*** linear algebra/
 Linear algebra tools
**** solver.sage (*#!)
 Method to solve a linear equation over Z with torsion
 - Make the code use left multiplication?
*** modular_forms/
 Code to analyze modular forms
**** elimination.sage (*+!)
 Methods for eliminating newforms
 - Add better tracking system for primes
 - Improve the elimination of l

**** newform wrapper.sage (*#!)
 Wrapper classes around newforms and a new method to get newforms
 - Can the argument minimal_coeffs of get_newforms be removed?
*** number_fields/
 Code to analyze number fields
**** dirichlet characters.sage (*#!)
 Methods related to dirichlet characters
**** field constructors.sage (*#!)
 Methods to make number fields
**** galois group.sage (*#!)
 Methods to change galois homomorphisms
 - Change name?
*** p-adics/
 Code related to p-adic numbers
**** pAdic_base.sage (*#!)
 A class giving easy acces to things needed for p-adic computations
**** pAdic_solver.sage (*#!)
 Methods for finding all pAdic roots of a polynomial up to a given
 precision
 - give_list is funky and only seems to work when K = L
 - quit_on_empty is not used?!
 - Improved algorithm???
**** pAdic_tree.sage (*#!)
 Classes for storing pAdic data in a tree like format
 - Method pAdicNode.sub_tree() is nowhere used and weird, remove?
 - Optimize _merge_with_list
 - Add sequence/set like behavior to pAdicNodeCollection
 - Add set like behavior to pAdicTree
*** polynomial/
 Code for working with polynomials
**** symmetric_polynomials.sage (*#!)
 Method for computing with a symmetric polynomial
** tests/
Code for (automated) testing
*** cleanup.sh (+)
Cleanup script
*** code/
Temporary directory for code to be tested
*** generate.sh
Script to generate code from a template
*** Q-curve sage vs magma.sage (-)
Speed test results between sage and magma newform computations
*** results/
Output directory for results (logs) of tests
*** templates/
Templates for tests
**** Q-curve with 2-3-isogeny.sage
Template for a test on a Q-curve with a 2 and a 3-isogeny
**** Q-curve with 2-isogeny.sage
Template for a test on a Q-curve with a 2-isogeny
**** Q-curve with 3-isogeny.sage
Template for a test on a Q-curve with a 3-isogeny
**** run.sage
Template for a wrapper script around a file.
**** test.sage (%)
Old test file
*** testrun_database.sh
A script that tests all .sage files in the database
*** testrun.sh
A script that tests all .sage files in the code directory
