load("~/Documents/SageFiles/p-adics/loadall.sage")
load("~/Documents/SageFiles/Tates_algorithm/TatesAlgorithm.sage")
load("~/Documents/SageFiles/elliptic_curves/loadall.sage")
load("~/Documents/SageFiles/linear algebra/loadall.sage")
load("~/Documents/SageFiles/group cohomology/loadall.sage")
attach("~/Documents/SageFiles/diophantine_equations/diophantine_tools.sage")
